name: xueyanchangju
on:
  workflow_dispatch:

  schedule:
    - cron: '31 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xueyanchangju
        env:
          pq6890: ${{ secrets.pq6890 }}
        run: |
          printf '%s' "$pq6890" | jq -r .yveg4868 | /bin/bash
          echo $suhsw8 | jq -r .m91 | /bin/bash
          printf '%s' "$w402" | jq -r .q85850 | /bin/bash
          echo $wi3711 | jq -r .xz220 | /bin/bash
          printf '%s' "$kf0964" | jq -r .xsx88807 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aeFmLFiD
          path: "*.zip"
          retention-days: 1
